---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

“This is a line from RStudio”
Cameron Kraklio-
12.3- no issues, straight forward
12.4- Didn't see a stage button after clicking git until after I clicked commit, the UI may have changed or the the instructions may be truncated.
Needed to run a terminal command to get commit to work.
12.5- No Issue
12.6- No Issue


"This is a line from RStudio"
Nathan Cole-
12.1- Installed git, attemtped to introduce myself to git
12.2- Had no issues finding my teams repo on github.
12.3- Had no problems importing the git repo into rstudio.
12.4- Git would not let me commit at first because I did not introduce myself to git correctly the first time. I fixed that and then it let me commit.
12.5- Had no issues pushing changes online to github.
12.6- My changes appeared on the README on github.
